# Generated by Django 5.0.6 on 2024-06-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_of",
            field=models.CharField(default="", max_length=13),
        ),
    ]
