# Generated by Django 5.0.6 on 2024-06-07 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0002_user_is_registered_alter_user_contact_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_of",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
